services:
    runner-dind:
        build:
            dockerfile: Dockerfile.runners
            args:
                VERSION: ${GITLAB_VERSION?error}
                NAME: 'dind'
        restart: always
        environment:
            TOKEN: ${RUNNER_TOKEN_DIND?error}
            DOMAIN_GITLAB: ${DOMAIN_GITLAB?error}
            DOCKER_VERSION: ${HOST_DOCKER_VERSION?error}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    runner-alpine:
        build:
            dockerfile: Dockerfile.runners
            args:
                VERSION: ${GITLAB_VERSION?error}
                NAME: 'alpine'
        restart: always
        environment:
            TOKEN: ${RUNNER_TOKEN_ALPINE?error}
            DOMAIN_GITLAB: ${DOMAIN_GITLAB?error}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    runner-debian-bookworm:
        build:
            dockerfile: Dockerfile.runners
            args:
                VERSION: ${GITLAB_VERSION?error}
                NAME: 'debian-bookworm'
        restart: always
        environment:
            TOKEN: ${RUNNER_TOKEN_DEBIAN_BOOKWORM?error}
            DOMAIN_GITLAB: ${DOMAIN_GITLAB?error}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    runner-debian-bullseye:
        build:
            dockerfile: Dockerfile.runners
            args:
                VERSION: ${GITLAB_VERSION?error}
                NAME: 'debian-bullseye'
        restart: always
        environment:
            TOKEN: ${RUNNER_TOKEN_DEBIAN_BULLSEYE?error}
            DOMAIN_GITLAB: ${DOMAIN_GITLAB?error}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
