services:
    gitlab:
        build: .
        container_name: gitlab
        restart: 'always'
        environment:
            # Domain names
            GITLAB_DOMAIN: ${GITLAB_DOMAIN?error}
            GITLAB_REGISTRY_DOMAIN: ${GITLAB_REGISTRY_DOMAIN}
            # Necessary for both the date format of backups
            # And the time shown on commits
            TZ: ${TIMEZONE:-UTC}
            # Only affect the text shown when cloning with SSH
            # And not the actual SSH port
            SSH_PORT: ${SSH_PORT:-22}
            # SAML/SSO
            SAML_IDP_CERT_FINGERPRINT: ${SAML_IDP_CERT_FINGERPRINT}
            SAML_IDP_SSO_TARGET_URL: ${SAML_IDP_SSO_TARGET_URL}
        ports:
            - '7080:80'
            - '7443:443'
            - '${SSH_PORT:-22}:22'
        volumes:
            # Standard volumes
            - './volumes/logs:/var/log/gitlab'
            - './volumes/data:/var/opt/gitlab'
            - './volumes/config:/etc/gitlab'
            # Overwrite
            - './crond:/crond'
            - './backups:/backups'
            - './certs:/certs'
            # Config files
            - './gitlab.rb:/etc/gitlab/gitlab.rb'
            - './init.rb:/assets/init.rb'
        # https://docs.gitlab.com/ee/install/docker/installation.html#install-gitlab-by-using-docker-compose
        shm_size: '256m'
