services:
    gitlab:
        build:
            context: .
            args:
                VERSION: ${GITLAB_VERSION?error}
                REVISION: ${GITLAB_REVISION?error}
        container_name: gitlab
        restart: 'no'
        environment:
            # Domain names
            GITLAB_DOMAIN: ${DOMAIN_GITLAB?error}
            GITLAB_REGISTRY_DOMAIN: ${DOMAIN_GITLAB_REGISTRY}
            # Necessary for both the date format of backups
            # And the time shown on commits
            TZ: ${TIMEZONE:-UTC}
            # Only affect the text shown when cloning with SSH
            # And not the actual SSH port
            SSH_PORT: ${SSH_PORT:-22}
            # SAML/SSO
            SAML_IDP_CERT_FINGERPRINT: ${SAML_IDP_CERT_FINGERPRINT}
            SAML_IDP_SSO_TARGET_URL: ${SAML_IDP_SSO_TARGET_URL}
        ports:
            - '${HTTP_PORT:-80}:80'
            - '${HTTPS_PORT:-443}:443'
            - '${SSH_PORT:-22}:22'
        volumes:
            # Standard volumes
            - './volumes/logs:/var/log/gitlab'
            - './volumes/data:/var/opt/gitlab'
            - './volumes/config:/etc/gitlab'
            # Overwrite
            - './backups:/backups'
            - './restore:/restore'
        # https://docs.gitlab.com/ee/install/docker/installation.html#install-gitlab-by-using-docker-compose
        shm_size: '256m'